# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  #encoding: unicode
  database: assignment_1
  username: postgres
  password: 12345 
  host: localhost
  port: 5432

test:
  adapter: postgresql
  #encoding: unicode
  database: assignment_1
  username: postgres
  password: 12345 
  host: localhost
  port: 5432
